# Generated by Django 4.2.1 on 2023-06-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_add_file_upload_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
